

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



// // app/layout.js (Before SEO Audit)

// export const metadata = {
//   title: "Portfolio",
//   description: "My personal website",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

// app/layout.js (After SEO Optimization)

// export const metadata = {
//   title: "Rafiul Goni Rayhan | Full-Stack Developer & Competitive Programmer",
//   description: "Explore the professional portfolio of Rafiul Goni Rayhan.
//    Specializing in React, Next.js, Tailwind CSS, MongoDB, and Full-Stack Web Development.",
//   keywords: ["Rafiul Goni Rayhan", "Full-Stack Developer", "Next.js Portfolio",
//      "BU CSE", "Competitive Programmer"],
//   openGraph: {
//     title: "Rafiul Goni Rayhan | Full-Stack Developer Portfolio",
//     description: "Showcasing modern web development projects and technical skills.",
//     url: "https://my-portfolio-virid-phi-51.vercel.app",
//     siteName: "Rayhan Portfolio",
//     images: [
//       {
//         url: "/portfolio-preview.png", 
//         width: 1200,
//         height: 630,
//       },
//     ],
//     locale: "en_US",
//     type: "website",
//   },
// };
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }



{/* <meta name="description" content="Explore the professional portfolio of Rafiul Goni Rayhan, a Full-Stack Developer specializing in React, Next.js, Node.js, and scalable web solutions." /> */}


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // data theme='light'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >


      
      <body className="min-h-full flex flex-col">
         <Navbar /> 
        {children}</body>
    </html>
  );
}
